using DodgeGame.Sprites;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace DodgeGame.Scenes
{
    public partial class DodgeScene : UserControl, IScene
    {
        // Constant values
        private const int planetHeight = 77;
        private const int starHeight = 10;

        // Member variables for storing the state of the game
        private readonly string username;
        private int score;
        private int lifeCount;
        private int livesLeft;
        private Navigator navigator;
        private List<BackgroundStar> stars;
        private List<Planet> planets;
        private Spaceship spaceship;
        private Random random;
        private MainWindow form;

        public DodgeScene(MainWindow _form, Navigator _navigator, string _username, int _lifeCount)
        {
            // Set up the controll (code generated by designer)
            InitializeComponent();

            // Init variables
            form = _form;
            username = _username;
            lifeCount = _lifeCount;
            navigator = _navigator;

            // Initialize a random number generator
            random = new Random();
        }

        public void Reset()
        {
            // Reset the score and lives
            score = 0;
            livesLeft = lifeCount;

            // Create a list of stars and a list of planets
            stars = new List<BackgroundStar>();
            planets = new List<Planet>();

            // Create a spaceship
            spaceship = new Spaceship();
        }

        public void Pause()
        {
            // Diable the timers
            PlanetTimer.Enabled = false;
            StarTimer.Enabled = false;
        }

        public void Resume()
        {
            // Enable the timers
            PlanetTimer.Enabled = true;
            StarTimer.Enabled = true;
        }

        public void DodgeScene_Paint(object sender, PaintEventArgs e)
        {
            var g = e.Graphics;

            // Clear the screen
            g.FillRectangle(Brushes.DarkSlateBlue, e.ClipRectangle);

            if (!form.MouseOverWindow)
            {
                var font = new Font(form.Font.FontFamily, 72);
                var format = new StringFormat
                {
                    Alignment = StringAlignment.Center,
                    LineAlignment = StringAlignment.Center
                };
                g.DrawString(
                    "Move The Mouse\nTo Over\nThe Window",
                    font,
                    Brushes.SkyBlue,
                    new PointF(e.ClipRectangle.Width / 2f, e.ClipRectangle.Height / 2f),
                    format);
            }

            // Loop through all of the stars and draw them
            foreach (var star in stars)
            {
                star.Draw(g);
            }

            // Loop through all of the planets and draw them
            foreach (var planet in planets)
            {
                planet.Draw(g);
            }

            // Draw the spaceship
            spaceship.Draw(g);

            // Draw the text
            g.DrawString($"Score: {score}", form.Font, Brushes.White, 5, 5);
            g.DrawString($"Lives: {livesLeft}", form.Font, Brushes.White, 5, 15 + form.Font.Size);
        }

        public void UpdateScene()
        {
            // Temporary measure to stop score from increasing when a dialog is showing
            // TODO: remove once we switch scenes instead of dialogs
            if (!PlanetTimer.Enabled)
                return;

            // Increment the score
            score++;

            // Remove the planets that have fallen off of the screen
            // We use a reverse for loop so that, when we remove planets, we dont skip any
            for (int i = planets.Count - 1; i >= 0; i--)
            {
                if (planets[i].Position.Y > form.ClientSize.Height)
                    planets.RemoveAt(i);
            }

            // Speed up the planets with the score
            Planet.Speed = 10 + score / 500f;

            // Loop through the stars and update them
            foreach (var star in stars)
            {
                star.Update(form.ClientSize);
            }

            // Loop through the planets and update them
            foreach (var planet in planets)
            {
                planet.Update(form.ClientSize);
            }

            // Update our spaceship
            spaceship.Update(form.ClientSize);

            // Check for collisions
            if (CheckCollisions())
            {
                // Remove all of the planets and decrement lifeCount
                planets.Clear();
                livesLeft--;

                // Disable updates while we prompt the user
                PlanetTimer.Enabled = false;
                StarTimer.Enabled = false;

                // Check if we are out of lives
                if (livesLeft <= 0)
                {
                    // Tell the user he/she is out of lives
                    MessageBox.Show(form, $"{username} finished with {score} points.", "Game Over");

                    // Reset the game
                    Reset();
                }
                else
                {
                    // Tell the user he/she died
                    MessageBox.Show(form, "You have been hit by a planet", "You died");
                }

                // Enable the timers again
                PlanetTimer.Enabled = true;
                StarTimer.Enabled = true;
            }

            // Redraw the scene
            Invalidate();
        }

        private bool CheckCollisions()
        {
            // Loop through all of the planets
            foreach (var planet in planets)
            {
                // And check if the intersect with our spaceship
                if (planet.CollidesWith(spaceship.Rectangle))
                    return true;
            }
            return false;
        }

        private void PlanetTimer_Tick(object sender, EventArgs e)
        {
            // Choose a random position for the new planet
            var xPosition = random.Next(0, form.ClientSize.Width - planetHeight);

            // Create a new planet and add it to the planets list
            var planet = new Planet(new PointF(xPosition, -planetHeight));
            planets.Add(planet);
        }

        private void StarTimer_Tick(object sender, EventArgs e)
        {
            // Choose a random position and speed for the new star
            var xPosition = random.Next(0, form.ClientSize.Width - starHeight);
            var speed = 0.25 + 0.5 * random.NextDouble();

            // Create a new star and add it to the stars list
            var star = new BackgroundStar(new PointF(xPosition, -starHeight), (float)speed);
            stars.Add(star);
        }

        public void DodgeScene_MouseMove(object sender, MouseEventArgs e)
        {
            // Move the spaceship to in line with the mouse
            spaceship.Position.X = e.X - spaceship.Size.Width / 2;
        }

        private void DodgeScene_Load(object sender, EventArgs e)
        {
            // Fill the window
            Dock = DockStyle.Fill;

            // Reset the game
            Reset();
        }
    }
}
