using DodgeGame.Sprites;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace DodgeGame.Scenes
{
    public partial class WelcomeScene : UserControl, IScene
    {
        private MainWindow form;
        private Navigator navigator;
        private string username;
        private int lifeCount;

        public WelcomeScene(MainWindow _form, Navigator _navigator, string _username, int _lifeCount)
        {
            // Set up the controll (code generated by designer)
            InitializeComponent();

            // Init variables
            form = _form;
            navigator = _navigator;
            username = _username;
            lifeCount = _lifeCount;
        }

        public void Pause() { }
        public void Resume() { }
        public void UpdateScene() { }

        private void WelcomeScene_Load(object sender, EventArgs e)
        {
            // Fill the window
            Dock = DockStyle.Fill;
        }

        private void PlayButton_Click(object sender, EventArgs e)
        {
            // Go to the DodgeScene
            navigator.Push(new DodgeScene(form, navigator, username, lifeCount));
        }

        private void SettingsButton_Click(object sender, EventArgs e)
        {
            // Go to the settings scene
        }

        private void HelpButton_Click(object sender, EventArgs e)
        {
            // Go to the help scene
        }

        private void QuitButton_Click(object sender, EventArgs e)
        {
            // Quit the game
            form.Close();
        }
    }
}
