using System;
using System.Windows.Forms;

namespace DodgeGame.Scenes
{
    public partial class WelcomeScene : UserControl, IScene
    {
        private MainWindow form;
        private Navigator navigator;

        public WelcomeScene(MainWindow _form, Navigator _navigator)
        {
            // Set up the controll (code generated by designer)
            InitializeComponent();

            // Init variables
            form = _form;
            navigator = _navigator;
        }

        public void Pause() { }
        public void Resume() { }
        public void UpdateScene() { }

        private void WelcomeScene_Load(object sender, EventArgs e)
        {
            // Fill the window
            Dock = DockStyle.Fill;
        }

        private void PlayButton_Click(object sender, EventArgs e)
        {
            // Go to the DodgeScene
            navigator.Push(new DodgeScene(form, navigator));
        }

        private void SettingsButton_Click(object sender, EventArgs e)
        {
            // Go to the settings scene
            navigator.Push(new SettingsScene(form, navigator));
        }

        private void HelpButton_Click(object sender, EventArgs e)
        {
            // Go to the help scene
            navigator.Push(new HelpScene(form, navigator));
        }

        private void QuitButton_Click(object sender, EventArgs e)
        {
            // Quit the game
            form.Close();
        }
    }
}
